$configs = $HOME/.config/hypr/configs

source=$configs/decorations.conf
source=$configs/autostart.conf
source=$configs/environments.conf
source=$configs/variables.conf
source=$configs/keybinds.conf
source=$configs/monitor.conf
