# Execute your favorite apps at launch
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = swaybg -m fill -i /home/inox/.config/hypr/wallpapers/wall1.jpg
exec-once = fcitx5 -d
