$mainMod = SUPER

$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = hyprlauncher

#Open applications
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
#Wofi
bind = SUPER, SPACE, exec, wofi --show drun

# Reload waybar
bind = $mainMod SHIFT, B, exec, pkill waybar && waybar

#Brightness
bind = SUPER, F5, exec, brightnessctl set 5%-
bind = SUPER, F6, exec, brightnessctl set +5%

bind = $mainMod SHIFT SPACE, 1, exec, swaybg -m fill -i ~/.config/hypr/wallpapers/wall1.jpg
bind = $mainMod SHIFT SPACE, 2, exec, swaybg -m fill -i ~/.config/hypr/wallpapers/wall2.jpg
bind = $mainMod SHIFT SPACE, 3, exec, swaybg -m fill -i ~/.config/hypr/wallpapers/wall3.jpg
bind = $mainMod SHIFT SPACE, 4, exec, swaybg -m fill -i ~/.config/hypr/wallpapers/wall4.jpg


# Print: chụp toàn màn hình, lưu file
bind = , Print, exec, grim ~/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png

# Shift + Print: chọn vùng, lưu file
bind = SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png

# Super + Shift + F: chụp toàn màn hình, copy clipboard
bind = $mainMod SHIFT, F, exec, grim - | wl-copy

# Super + Shift + S: chọn vùng, lưu file + copy clipboard
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy

# ===== AUDIO CONTROL ASUS GL552JX =====
# Super + F12 → Tăng âm lượng (max 150%)
bind = SUPER, F12, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+

# Super + F11 → Giảm âm lượng
bind = SUPER, F11, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Super + F10 → Mute / unmute
bind = SUPER, F10, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
